# Where the RBAC commands (pveum) should run (ONE node only)
pve_rbac_node: "pve01"

# CSV with columns:
# username,realm,enabled,expire,name,groups,password_hash,shell
users_csv_path: "{{ playbook_dir }}/files/users.csv"

# Default ACL to apply to all CSV users (optional)
pve_acl_default:
  enabled: true
  path: "/pool/Network"     # "/", "/dc", "/pool/<id>", "/vms/<vmid>", "/storage/<id>"
  role: "dart_network_remote"

# Pools to ensure exist (optional)
pve_pools:
  - name: "Network"
    comment: "Created by Ansible"

# Additional PVE groups to create (optional)
pve_groups_extra: []

# Optional: define custom PVE roles (used by roles/roles)
# pve_custom_roles:
#   - name: "PowerConsoleOnly"
#     privs: "VM.Console VM.PowerMgmt VM.Audit"
